# Change these first
owner: thomvh # Your GitHub username
repo: thvmh-uptime # Your Github repository name

# Add your sites here
sites:
  - name: STRMRocks Plex
    url: https://plex.strm.rocks
  - name: x5i5 Plex
    url: https://plex.x5i5.stream
  - name: x5i5 Plex2
    url: https://plex2.x5i5.stream  

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: status.thvmh.nl
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /thvmh-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Thvmh Uptime
  introTitle: ""
  introMessage: 
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
