# Change these first
owner: thomvh # Your GitHub username
repo: thvmh-uptime # Your Github repository name

# Add your sites here
sites:
  - name: STRMRocks Plex
    url: $STRM_PLEX
  - name: x5i5 Plex
    url: $X5I5_PLEX
  - name: x5i5 Plex2
    url: $X5I5_PLEX2

status-website:
  #publish: true
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.thvmh.nl
  # Uncomment the following line if you don't have a custom domain and add your repo name
  #baseUrl: /thvmh-uptime
  #apiBaseUrl: api.github.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Thvmh Uptime
  introTitle: "Status of Thvmh services"
  introMessage: Check the status of the Thvmh provided services
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
